services:
  bot:
    build:
      context: .
      dockerfile: src/LinkTracker.Bot/Dockerfile
    ports:
      - "5100:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - BotConfiguration__BotToken=${TELEGRAM_BOT_TOKEN}
      - BotConfiguration__ScrapperUrl=http://scrapper:8080
    depends_on:
      - scrapper

  scrapper:
    build:
      context: .
      dockerfile: src/LinkTracker.Scrapper/Dockerfile
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - BotUrl=http://bot:8080
      - Database__AccessType=SQL
      - Database__ConnectionString=Host=postgres;Port=5432;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}
      - Database__RunMigrations=true
      - Scrapper__GitHubToken=${GITHUB_TOKEN}
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:16
    container_name: linktracker-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  postgres-data: