name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build the Bot image
      run: docker build . --file src/LinkTracker.Bot/Dockerfile --tag linktracker-bot:$(date +%s)

    - name: Build the Scrapper image
      run: docker build . --file src/LinkTracker.Scrapper/Dockerfile --tag linktracker-scrapper:$(date +%s)
